/* ===================== DATA: breeds, tack catalog (43 real items + 5 academy originals), lands, lines ===================== */
BASES.greydun = { n: 'Grey dun', base: '#b8b4a8', mane: '#efe9dc', dun: true };
const BREEDS = [
  { id: 'appaloosa', n: 'Appaloosa', star: 1, from: 'USA (Pacific Northwest)', pats: ['leopard', 'fewspot', 'blanket', 'snowcap', 'snowflake', 'frost', 'varnish'], bases: ['chestnut', 'bay', 'black', 'palomino', 'grey'], fact: 'First bred by the Nez Perce (Nimíipuu) people, who got horses around 1730 and chose the best ones for breeding. Settlers called them "Palouse horses" after the Palouse River. The Appaloosa Horse Club began in 1938.' },
  { id: 'nezperce', n: 'Nez Perce Horse', from: 'USA (Lapwai, Idaho)', pats: ['blanket', 'leopard', 'solid'], bases: ['bay', 'black', 'chestnut'], fact: 'A newer breed from the Nez Perce Tribe\u2019s horse program: Appaloosa mixed with Akhal-Teke.' },
  { id: 'knabstrupper', n: 'Knabstrupper', from: 'Denmark', pats: ['leopard', 'blanket', 'solid'], bases: ['bay', 'black', 'chestnut'], fact: 'Spotted like an Appaloosa! The breed began with a spotted mare in 1812.' },
  { id: 'poa', n: 'Pony of the Americas', from: 'USA (Iowa)', pats: ['leopard', 'blanket', 'snowflake', 'fewspot'], bases: ['chestnut', 'bay', 'black', 'palomino'], fact: 'A kid-sized pony with Appaloosa spots, started in 1954.' },
  { id: 'arabian', n: 'Arabian', from: 'Arabian Peninsula', coats: [['grey'], ['bay', 0, { star: 1 }], ['chestnut', 0, { blaze: 1, socks: [1, 0, 0, 1] }], ['black']], fact: 'One of the oldest horse breeds. Arabians have a dished face and carry their tails high.' },
  { id: 'andalusian', n: 'Andalusian', from: 'Spain', coats: [['grey', 0, { mane: 'long' }], ['dapple', 0, { mane: 'long' }], ['bay', 0, { mane: 'long' }], ['black', 0, { mane: 'long' }]], fact: 'Spain\u2019s proud "pure Spanish horse," famous for parades and dressage.' },
  { id: 'lusitano', n: 'Lusitano', from: 'Portugal', coats: [['grey', 0, { mane: 'long' }], ['bay', 0, { mane: 'long' }], ['buckskin', 0, { mane: 'long' }]], fact: 'A brave, graceful cousin of the Andalusian.' },
  { id: 'lipizzaner', n: 'Lipizzaner', from: 'Austria / Slovenia', coats: [['grey'], ['darkfoal']], fact: 'Lipizzaners are born dark and turn white as they grow up. The Lipica stud farm began in 1580.' },
  { id: 'friesian', n: 'Friesian', from: 'Netherlands', coats: [['black', 0, { feather: 1, mane: 'long' }]], fact: 'Shiny black with long, wavy manes and feathery feet. Friesians are always black.' },
  { id: 'marwari', n: 'Marwari', from: 'India (Rajasthan)', coats: [['bay', 0, { ears: 'curl', star: 1 }], ['chestnut', 0, { ears: 'curl', blaze: 1 }], ['grey', 0, { ears: 'curl' }], ['chestnut', 'tobiano', { ears: 'curl' }]], fact: 'Its ears curve inward so much that the tips can touch!' },
  { id: 'mongolian', n: 'Mongolian Horse', from: 'Mongolia', coats: [['dun'], ['bay'], ['grey'], ['chestnut']], fact: 'Small, tough and fast. Mongolia has about as many horses as people, or even more!' },
  { id: 'akhalteke', n: 'Akhal-Teke', from: 'Turkmenistan', coats: [['golden'], ['palomino', 0, { sheen: 1 }], ['bay', 0, { sheen: 1 }], ['black', 0, { sheen: 1 }]], fact: 'Its coat shines like metal. It is shown on Turkmenistan\u2019s national emblem.' },
  { id: 'thoroughbred', n: 'Thoroughbred', from: 'England', coats: [['bay', 0, { star: 1 }], ['chestnut', 0, { blaze: 1, socks: [1, 0, 1, 0] }], ['black'], ['grey']], fact: 'A racehorse breed. All Thoroughbreds trace back to three famous stallions from the 1700s.' },
  { id: 'quarter', n: 'American Quarter Horse', from: 'USA', coats: [['palomino', 0, { blaze: 1, socks: [1, 0, 1, 0] }], ['buckskin'], ['sorrel', 0, { star: 1 }], ['bay'], ['blueroan'], ['redroan']], fact: 'The fastest horse over a quarter mile.' },
  { id: 'paint', n: 'American Paint Horse', from: 'USA', pats: ['tobiano', 'overo', 'tovero'], bases: ['bay', 'black', 'chestnut', 'palomino'], m: { socks: [1, 1, 1, 1] }, fact: 'A stock horse with big pinto patches.' },
  { id: 'mustang', n: 'Mustang', from: 'USA (the West)', coats: [['bay'], ['dun'], ['buckskin'], ['palomino'], ['blueroan'], ['black'], ['bay', 'tobiano', { socks: [1, 1, 1, 1] }]], fact: 'Free-roaming horses of the American West, whose ancestors were Spanish horses.' },
  { id: 'criollo', n: 'Criollo', from: 'Argentina', coats: [['dun'], ['bay'], ['redroan'], ['bay', 'tobiano', { socks: [1, 1, 1, 1] }]], fact: 'The gaucho\u2019s tough horse. Two Criollos, Mancha and Gato, carried a rider from Buenos Aires to Washington, D.C. in the 1920s.' },
  { id: 'icelandic', n: 'Icelandic Horse', from: 'Iceland', coats: [['sorrel', 0, { mane: 'long' }], ['bay', 0, { mane: 'long' }], ['black', 0, { mane: 'long' }], ['palomino', 0, { mane: 'long' }], ['dun', 0, { mane: 'long' }], ['grey', 0, { mane: 'long' }], ['bay', 'tobiano', { mane: 'long', socks: [1, 1, 1, 1] }]], fact: 'It has a special extra gait called the tölt. No other horses have been brought into Iceland for over 1,000 years.' },
  { id: 'shetland', n: 'Shetland Pony', from: 'Scotland (Shetland Islands)', coats: [['bay'], ['black'], ['chestnut'], ['palomino'], ['black', 'tobiano', { socks: [1, 1, 1, 1] }], ['dapple']], fact: 'Tiny but very strong.' },
  { id: 'shire', n: 'Shire', from: 'England', coats: [['black', 0, { feather: 1, socks: [1, 1, 1, 1], blaze: 1 }], ['bay', 0, { feather: 1, socks: [1, 1, 1, 1], blaze: 1 }], ['grey', 0, { feather: 1, socks: [1, 1, 1, 1] }]], fact: 'One of the tallest horse breeds in the world.' },
  { id: 'clydesdale', n: 'Clydesdale', from: 'Scotland', coats: [['bay', 0, { feather: 1, socks: [1, 1, 1, 1], blaze: 1 }], ['brown', 0, { feather: 1, socks: [1, 1, 1, 1], blaze: 1 }], ['black', 0, { feather: 1, socks: [1, 1, 1, 1], blaze: 1 }]], fact: 'A gentle giant with fluffy "feathers" on its feet.' },
  { id: 'haflinger', n: 'Haflinger', from: 'Austria / Italy', coats: [['sorrel', 0, { blaze: 1 }]], fact: 'Golden with a blond mane: a mountain horse. Haflingers are always chestnut with a flaxen mane.' },
  { id: 'fjord', n: 'Norwegian Fjord', from: 'Norway', coats: [['fjord'], ['greydun', 0, { mane: 'roach' }]], fact: 'Its mane is trimmed short so the dark stripe in the middle shows. Fjords always come in dun shades.' },
  { id: 'camargue', n: 'Camargue', from: 'France', coats: [['grey'], ['darkfoal']], fact: '"Horses of the sea" from the marshes. They are born dark and turn white.' },
  { id: 'morgan', n: 'Morgan', from: 'USA', coats: [['bay', 0, { star: 1 }], ['black'], ['chestnut', 0, { blaze: 1 }]], fact: 'Every Morgan traces back to one little stallion named Figure, owned by Justin Morgan.' },
  { id: 'percheron', n: 'Percheron', from: 'France', coats: [['dapple', 0, { feather: 0 }], ['black']], fact: 'A big, strong draft horse from the Perche region.' },
];
const BREED_BY = Object.fromEntries(BREEDS.map(b => [b.id, b]));
function breedCoats(br) {
  if (br.pats) { const out = []; for (const p of br.pats) for (const b of br.bases) out.push({ b, p, m: Object.assign({}, br.m || {}, p === 'blanket' || p === 'snowcap' ? { star: 1 } : {}) }); return out; }
  return br.coats.map(([b, p, m]) => ({ b, p: p || 'solid', m: m || {} }));
}
function coatName(spec) { const B = BASES[spec.b]; if (!spec.p || spec.p === 'solid') return B.n; if (spec.p === 'leopard' || spec.p === 'fewspot') return PATTERNS[spec.p] + ' (' + B.n.toLowerCase() + ' spots)'; return PATTERNS[spec.p] + ' on ' + B.n.toLowerCase(); }
const _mk = makeCoat; // sheen override support
makeCoat = function (spec) { const c = _mk(spec); if (spec.m && spec.m.sheen) c.sheen = true; return c; };

/* ---------- Tack catalog ---------- */
const CATS = [
  { id: 'saddle', n: 'Saddles', col: '#8a5cd6' }, { id: 'pad', n: 'Blankets', col: '#3f6fd8' }, { id: 'bridle', n: 'Bridles', col: '#2fa39a' },
  { id: 'chest', n: 'Chest', col: '#e8504a' }, { id: 'mane', n: 'Mane & Tail', col: '#ff8c2e' }, { id: 'plume', n: 'Plumes', col: '#d94f9a' },
  { id: 'garland', n: 'Flowers', col: '#ff5a7a' }, { id: 'academy', n: 'Academy', col: '#7446c4' },
];
const LEATHER = ['#8a4f2a', '#5a3420', '#2a2025', '#c8925a'];
const IT = (o) => o;
const ITEMS = [
  // ---- Saddles
  IT({ id: 'S1', cat: 'saddle', slot: 'saddle', n: 'Silver Parade Saddle', where: 'Hollywood, California, USA', when: '1920s to 1950s (about 100 years ago)', who: 'Saddle maker Edward H. Bohlin, for movie cowboys and parade riders', text: 'Edward Bohlin came to America from Sweden and made saddles covered with real silver shapes called conchos. Movie cowboys loved them, and they sparkled in the Rose Parade!', pin: [-118, 34], ch: [{ n: 'Leather', o: ['#2a2025', '#6b3e22', '#c8925a', '#f2ead8'] }, { n: 'Metal', o: ['#dfe6ee', '#f2c14e'] }], draw: (c) => sWestern(c[0], c[1], { conchos: 1 }) }),
  IT({ id: 'S2', cat: 'saddle', slot: 'saddle', n: 'Spanish Vaquera Saddle', where: 'Andalusia, southern Spain', when: 'Used for hundreds of years, and still today', who: 'Spanish vaqueros (cattle riders)', text: 'Made for long days working cattle. It has a fluffy sheepskin seat and a fringed blanket folded across the front. In competitions the saddle must be black. Spanish riding later traveled to the Americas.', pin: [-5, 37], ch: [{ n: 'Leather', o: ['#231c22', '#8a5a32'] }, { n: 'Blanket', o: ['#c0392b', '#2e86de', '#2fa36b', '#f2b632'] }], draw: (c) => sVaquera(c[0], c[1]) }),
  IT({ id: 'S3', cat: 'saddle', slot: 'saddle', n: 'Mexican Charro Saddle', where: 'Mexico', when: 'Grew on big ranches in the 1700s and 1800s', who: 'Charros, Mexico\u2019s skilled horse riders', text: 'Charros decorate saddles with piteado, embroidery made with a strong plant thread called pita. Charrería is often called Mexico\u2019s national sport. In 2016 UNESCO named it a world treasure.', pin: [-102, 21], ch: [{ n: 'Leather', o: ['#c8925a', '#6b3e22', '#2a2025'] }, { n: 'Thread', o: ['#dfe6ee', '#f6f1e6', '#f2c14e'] }], draw: (c) => sWestern(c[0], c[1], { piteado: 1, charroHorn: 1 }) }),
  IT({ id: 'S4', cat: 'saddle', slot: 'saddle', n: 'California Vaquero Saddle', where: 'Alta California (then part of New Spain, later Mexico)', when: '1700s to 1800s', who: 'California vaqueros', text: 'Its sturdy horn held a rope while working cattle. Later cowboys learned from vaqueros, and their saddles grew into the Western saddle.', pin: [-120, 36], ch: [{ n: 'Leather', o: ['#8a5a32', '#c8925a', '#2a2025'] }], draw: (c) => sWestern(c[0], '#b9a07a', { plain: 1, tapaderos: 1 }) }),
  IT({ id: 'S5', cat: 'saddle', slot: 'saddle', n: 'English Hunt Saddle', where: 'England', when: '1700s, and still used today', who: 'Riders crossing the countryside on hunts', text: 'Riders needed to jump hedges and ditches, so saddles became flatter with low fronts and backs. Around 1900, Italian rider Federico Caprilli taught the "forward seat" used for jumping today. This is Kimber\u2019s own saddle: she rides English!', pin: [-1.5, 52.5], ch: [{ n: 'Leather', o: ['#8a4f2a', '#6b3420', '#2a2025'] }], draw: (c) => sEnglish(c[0]) }),
  IT({ id: 'S6', cat: 'saddle', slot: 'saddle', n: 'Sidesaddle', where: 'Europe', when: 'For hundreds of years; an extra pommel was added in France around 1830', who: 'Lady riders', text: 'Riders sat with both legs on one side. Around 1830 a second hook, the "leaping head," was added (often credited to Jules Pellier). It helped riders stay on when galloping and jumping. Kimber gets a long riding skirt with it!', pin: [2.3, 48.9], ch: [{ n: 'Leather', o: ['#8a4f2a', '#2a2025'] }, { n: 'Skirt', o: ['#33407e', '#2a2630', '#7a2b4a', '#2f5e3a'] }], draw: (c) => sEnglish(c[0], { side: 1 }) }),
  IT({ id: 'S7', cat: 'saddle', slot: 'saddle', n: 'Mongolian Saddle', where: 'Mongolia', when: 'Used for many centuries', who: 'Mongolian herders', text: 'A wooden saddle with a high front and back, often painted bright colors and decorated with silver. Mongolian children learn to ride when they are very young.', pin: [105, 47], ch: [{ n: 'Paint', o: ['#c0392b', '#ff8c2e', '#2e86de', '#2fa36b'] }, { n: 'Studs', o: ['#e6ecf2'] }], draw: (c) => sMongolian(c[0], c[1]) }),
  IT({ id: 'S8', cat: 'saddle', slot: 'saddle', n: 'Gaucho Recado', where: 'Pampas grasslands of Argentina and Uruguay', when: '1700s and 1800s, and still used', who: 'Gauchos, the cowboys of the Pampas', text: 'A saddle made of layers! A soft sheepskin called a pellón goes on top. Fancy gauchos added silver.', pin: [-60, -35], ch: [{ n: 'Sheepskin', o: ['#f3e9d6', '#2b2730', '#ffffff'] }, { n: 'Trim', o: ['#dfe6ee'] }], draw: (c) => sRecado(c[0], c[1]) }),
  IT({ id: 'S9', cat: 'saddle', slot: 'saddle', n: 'Lipizzaner School Saddle', where: 'Vienna, Austria', when: 'The Spanish Riding School dates to 1565', who: 'Riders of the Spanish Riding School', text: 'For shows, the white stallions wear a big saddle made of white buckskin. It is fancier than their everyday training saddle.', fixed: 'White or cream only, because that is the tradition.', pin: [16.4, 48.2], ch: [{ n: 'Buckskin', o: ['#f6f1e6', '#efe2c4'] }], draw: (c) => sSchool(c[0]) }),
  IT({ id: 'S10', cat: 'saddle', slot: 'saddle', n: 'Japanese Lacquered Saddle', where: 'Japan', when: '1100s to 1300s (Kamakura period)', who: 'Samurai riders', text: 'Lacquered saddles were shiny and decorated with mother-of-pearl. The iron stirrups look like big slippers. Riders still use this kind of saddle in yabusame (archery on horseback), done at a shrine in Kamakura since 1187.', pin: [139.5, 35.3], ch: [{ n: 'Lacquer', o: ['#1d1a21', '#a8202a'] }, { n: 'Trim', o: ['#f2c14e', '#f6f1e6'] }], draw: (c) => sJapan(c[0], c[1]) }),
  IT({ id: 'S11', cat: 'saddle', slot: 'saddle', n: 'Ottoman Jeweled Saddle', where: 'Ottoman Empire (today\u2019s Türkiye)', when: '1500s to 1700s', who: 'Sultans and palace riders', text: 'Palace saddles were covered with velvet, gold thread and gemstones. You can still see some in the Topkapı Palace Museum in Istanbul.', pin: [29, 41], ch: [{ n: 'Velvet', o: ['#a8202a', '#1f6f3c', '#24408e'] }, { n: 'Gold', o: ['#f2c14e'] }], draw: (c) => sOttoman(c[0], c[1]) }),
  // ---- Blankets & caparisons
  IT({ id: 'B1', cat: 'pad', slot: 'pad', n: 'Jousting Caparison', where: 'England, France and other parts of Europe', when: '1200s to 1400s (about 700 years ago)', who: 'Knights at tournaments', text: 'A caparison is a big cloth coat for a horse. Its colors showed the knight\u2019s coat of arms, so everyone could tell who was who!', pin: [2, 48], thumb: [0, -112, 0.72], ch: [{ n: 'Color 1', o: ['#3f6fd8', '#c0392b', '#2fa36b', '#7446c4', '#2a2630'] }, { n: 'Color 2', o: ['#f2c14e', '#f6f1e6', '#c0392b', '#3f6fd8'] }, { n: 'Emblem', o: ['star', 'flower', 'horseshoe', 'moon', 'heart'], emblem: 1 }], draw: (c) => bCaparison(c[0], c[1], c[2]) }),
  IT({ id: 'B2', cat: 'pad', slot: 'pad', n: 'Lipizzaner Shabrack', where: 'Vienna, Austria', when: 'Spanish Riding School tradition', who: 'Spanish Riding School riders', text: 'Red-and-gold cloths are for most shows. Green-and-gold is for "in-hand" work and the big jumps. The number of gold stripes shows the rider\u2019s rank.', fixed: 'Only red-and-gold or green-and-gold, like the real ones.', pin: [16.4, 48.2], ch: [{ n: 'Colors', o: [['#b3162a', '#f2c14e'], ['#1f6f3c', '#f2c14e']] }], draw: (c) => bShabrack(c[0]) }),
  IT({ id: 'B3', cat: 'pad', slot: 'pad', n: 'Navajo-style Saddle Blanket', honor: 'Honoring Diné (Navajo) weavers', where: 'U.S. Southwest', when: 'From the 1860s to today', who: 'Diné (Navajo) weavers', text: 'Diné weavers made tough wool saddle blankets for their own horses, sometimes using wool from Churro sheep. Weavers still make them today.', note: 'This simple pattern is inspired by museum blankets. It does not copy any one weaver\u2019s design.', pin: [-109, 36], ch: [{ n: 'Wool', o: [['#c83e2c', '#2c2a3a', '#fbf3e4', '#8a8a94'], ['#ff8c2e', '#2fa39a', '#7446c4', '#f2b632']], labels: ['Natural colors', 'Bright yarns'] }], draw: (c) => bNavajo(c[0]) }),
  IT({ id: 'B4', cat: 'pad', slot: 'pad', n: 'Ottoman Gold-Thread Saddle Cloth', where: 'Ottoman Empire', when: '1500s to 1600s', who: 'Palace horsemen', text: 'Silk cloth embroidered with shiny metal thread. Museums like the V&A in London keep some.', pin: [29, 41], ch: [{ n: 'Silk', o: ['#a8202a', '#24408e', '#1f6f3c'] }, { n: 'Gold', o: ['#f2c14e'] }], draw: (c) => bOtCloth(c[0], c[1]) }),
  IT({ id: 'B5', cat: 'pad', slot: 'pad', n: 'Pazyryk Felt Saddle Cover', where: 'Altai Mountains, Siberia', when: 'About 2,400 years ago', who: 'Nomads of the Pazyryk culture', text: 'Found frozen in ice in ancient burial mounds! It has felt cut-outs of griffins. Today it is in the Hermitage Museum.', pin: [87, 50], ch: [{ n: 'Felt', o: ['#b8352f', '#2e5aa8', '#d9a23a'] }, { n: 'Cut-outs', o: ['#f2c14e', '#f6f1e6'] }], draw: (c) => bPazyryk(c[0], c[1]) }),
  IT({ id: 'B6', cat: 'pad', slot: 'pad', n: 'Marwari Wedding Costume', where: 'Rajasthan, India', when: 'A long tradition, still loved today', who: 'Wedding families', text: 'In many North Indian weddings, the groom rides a decorated horse in a happy parade called the baraat. The cloth sparkles with mirrors, tassels and bells.', pin: [73, 26], ch: [{ n: 'Cloth', o: ['#d7263d', '#ff8c2e', '#ff5fa2'] }, { n: 'Gold', o: ['#f6c343'] }], draw: (c) => bMarwari(c[0], c[1]) }),
  IT({ id: 'B7', cat: 'pad', slot: 'pad', n: 'Quilted Saddle Pad', where: 'Everywhere riders ride', when: 'Today', who: 'Everyday riders', text: 'A soft pad that keeps the horse\u2019s back comfy under the saddle.', pin: [-90, 40], ch: [{ n: 'Color', o: ['#9b5de5', '#ff6f91', '#4cc3ff', '#6bd66b', '#ffd93d', '#f6f1e6', '#2a2630'] }], draw: (c) => bPad(c[0]) }),
  // ---- Bridles & headgear
  IT({ id: 'H1', cat: 'bridle', slot: 'bridle', n: 'Mosquero Fringe', where: 'Spain', when: 'Traditional, still used', who: 'Spanish riders', text: 'A fringe of horsehair, leather or silk hangs from the browband. It swishes flies away from the horse\u2019s eyes!', pin: [-5, 37], ch: [{ n: 'Fringe', o: ['#1d1a21', '#c0392b', ['#c0392b', '#1d1a21']], labels: ['Black', 'Red', 'Mixed'] }], draw: (c, p) => bridleBase(p, '#2a2025', '#c9d1da', { fringe: c[0] }) }),
  IT({ id: 'H2', cat: 'bridle', slot: 'bridle', n: 'Lipizzaner Gold Bridle', where: 'Vienna, Austria', when: 'Spanish Riding School tradition', who: 'The white stallions of the Spanish Riding School', text: 'A gold-plated double bridle that the white stallions wear only for performances.', fixed: 'Gold and white only, like the real one.', pin: [16.4, 48.2], ch: [{ n: 'Gold', o: ['#f2c14e'] }], draw: (c, p) => bridleBase(p, '#f6f1e6', c[0], { conchos: 1, double: 1 }) }),
  IT({ id: 'H3', cat: 'bridle', slot: 'bridle', n: 'Silver Concho Headstall', where: 'Hollywood and the Rose Parade, USA', when: '1920s to 1950s', who: 'Parade riders and movie cowboys', text: 'It matches the silver parade saddle, with silver conchos on every strap.', pin: [-118, 34], ch: [{ n: 'Leather', o: ['#2a2025', '#6b3e22'] }, { n: 'Metal', o: ['#dfe6ee', '#f2c14e'] }], draw: (c, p) => bridleBase(p, c[0], c[1], { conchos: 1 }) }),
  IT({ id: 'H4', cat: 'bridle', slot: 'bridle', n: 'Plateau-style Beaded Headpiece', honor: 'Honoring Nimíipuu (Nez Perce) artists', where: 'Columbia River Plateau (Idaho, Washington, Oregon)', when: '1800s to today', who: 'Nez Perce families', text: 'Nez Perce artists bead beautiful horse regalia for parades and celebrations. A beaded horse mask from about 1865 is in the Smithsonian. Families still make them and pass them down today.', note: 'These colors come from real beadwork. The simple shapes are inspired by museum pieces and do not copy any family\u2019s design.', pin: [-117, 46], ch: [{ n: 'Beads', o: [['#7ec8e3', '#b3162a', '#f2c14e'], ['#2e5aa8', '#b3162a', '#f6f1e6'], ['#3f9a5a', '#ff8fb1', '#f6f1e6']], labels: ['Sky blue, red, gold', 'Blue and red', 'Green and pink'] }], draw: (c, p) => bridleBase(p, '#b3162a', '#c9d1da', { beads: c[0] }) }),
  IT({ id: 'H5', cat: 'bridle', slot: 'mask', n: 'Pazyryk Antler Mask', where: 'Altai Mountains, Siberia', when: 'About 2,300 to 2,500 years ago', who: 'Pazyryk nomads', text: 'Horses wore felt and leather masks with antlers, so they looked like magical deer! One was found frozen in ice.', pin: [87, 50], thumb: [104, -270, 0.95], ch: [{ n: 'Felt', o: ['#b8352f', '#2e5aa8', '#3f7a4a'] }, { n: 'Trim', o: ['#f2c14e'] }], draw: (c, p) => hAntler(p, c[0], c[1]) }),
  IT({ id: 'H6', cat: 'bridle', slot: 'mask', n: 'Knight\u2019s Chanfron', where: 'Europe', when: 'From the mid-1200s', who: 'Knights', text: 'A chanfron is a shield for a horse\u2019s face, made of hard leather or metal. Fancy ones were made for parades.', pin: [10, 48], ch: [{ n: 'Steel', o: ['#c9d1da'] }, { n: 'Trim', o: ['#f2c14e', '#c9d1da'] }], draw: (c, p) => hChanfron(p, c[0], c[1]) }),
  IT({ id: 'H7', cat: 'bridle', slot: 'scarf', n: 'Naadam Blue Scarf (khadag)', where: 'Mongolia', when: 'A long tradition', who: 'Naadam festival riders', text: 'A blue silk scarf means respect and the blue sky. In Naadam races the riders are kids, and the horse is the champion! A scarf may be tied on a winning horse.', fixed: 'Blue, like the real tradition.', pin: [105, 47], thumb: [90, -200, 1.05], ch: [{ n: 'Silk', o: ['#4f9be8'] }], draw: (c, p) => hKhadag(p, c[0]) }),
  IT({ id: 'H8', cat: 'bridle', slot: 'bridle', n: 'English Snaffle Bridle', where: 'Everywhere', when: 'Today', who: 'Everyday riders', text: 'A simple leather bridle. The bit is a gentle snaffle.', pin: [-1.5, 52.5], ch: [{ n: 'Leather', o: ['#5a3420', '#2a2025'] }], draw: (c, p) => bridleBase(p, c[0], '#c9d1da') }),
  // ---- Chest
  IT({ id: 'C1', cat: 'chest', slot: 'chest', n: 'Plateau-style Beaded Martingale', honor: 'Honoring Nimíipuu (Nez Perce) artists', where: 'Columbia River Plateau', when: '1800s to today', who: 'Nez Perce families, the people who first bred the Appaloosa', text: 'A beaded chest piece on red wool, often with little bells. Museum pieces from the 1870s to 1890s have triangles and diamonds. Families still ride in them at parades like the Pendleton Round-Up.', note: 'These colors come from real beadwork. The simple shapes are inspired by museum pieces and do not copy any family\u2019s design.', pin: [-117, 46], ch: [{ n: 'Beads', o: [['#7ec8e3', '#b3162a', '#f2c14e'], ['#2e5aa8', '#b3162a', '#f6f1e6'], ['#3f9a5a', '#ff8fb1', '#f6f1e6']], labels: ['Sky blue, red, gold', 'Blue and red', 'Green and pink'] }], draw: (c) => cBeaded(c[0]) }),
  IT({ id: 'C2', cat: 'chest', slot: 'chest', n: 'Silver Breast Collar', where: 'Hollywood and the Rose Parade, USA', when: '1920s to 1950s', who: 'Parade riders', text: 'The front of a silver parade set. It keeps the saddle from sliding back, and it sparkles!', pin: [-118, 34], ch: [{ n: 'Leather', o: ['#2a2025', '#6b3e22'] }, { n: 'Metal', o: ['#dfe6ee', '#f2c14e'] }], draw: (c) => cBreast(c[0], c[1]) }),
  IT({ id: 'C3', cat: 'chest', slot: 'chest', n: 'Goldzeug', where: 'Vienna, Austria', when: 'Spanish Riding School tradition', who: 'The white stallions at performances', text: 'A gold-plated breastplate and tail strap worn by the white stallions at performances. Goldzeug means "gold gear" in German.', fixed: 'Gold only.', pin: [16.4, 48.2], thumb: [-4, -132, 0.62], ch: [{ n: 'Gold', o: ['#f2c14e'] }], draw: (c) => cGoldzeug(c[0]) }),
  IT({ id: 'C4', cat: 'chest', slot: 'chest', n: 'Horse Brasses', where: 'England', when: 'Mid-1800s to about 1914', who: 'Working horses and their drivers', text: 'Shiny brass badges hung on working horses\u2019 harness. Drivers were proud of them! Many were made in Walsall and Birmingham.', pin: [-1.9, 52.5], ch: [{ n: 'Brass', o: ['#e8b84a'] }], draw: () => cBrasses() }),
  IT({ id: 'C5', cat: 'chest', slot: 'chest', n: 'Tang Apricot-Leaf Pendants', where: 'China', when: 'Tang dynasty, 618 to 907', who: 'Riders shown on Tang pottery horses', text: 'Old Tang pottery horses show harness straps hung with tassels and leaf-shaped pendants.', pin: [109, 34], thumb: [-4, -132, 0.62], ch: [{ n: 'Leaves', o: ['#3f9a5a', '#f6f1e6', '#f2c14e'] }, { n: 'Metal', o: ['#f2c14e'] }], draw: (c) => cTang(c[0], c[1]) }),
  IT({ id: 'C6', cat: 'chest', slot: 'chest', n: 'Drum Horse Banners', where: 'London, England', when: 'The silver drums were presented in 1805 and 1831', who: 'The Household Cavalry', text: 'Big drum horses carry two solid-silver kettledrums. The rider steers with reins tied to the stirrups, because his hands are busy drumming!', pin: [-0.1, 51.5], thumb: [68, -130, 0.95], ch: [{ n: 'Banner', o: [['#24408e', '#f2c14e'], ['#b3162a', '#f2c14e']], labels: ['Royal blue and gold', 'Red and gold'] }], draw: (c) => cDrums(c[0]) }),
  // ---- Mane & tail
  IT({ id: 'M1', cat: 'mane', slot: 'mane', n: 'Hunter Braids', where: 'England, then the USA', when: 'From fox-hunting days to today\u2019s hunter shows', who: 'Show riders', text: 'Neat little braids keep the mane out of the way and look smart in the show ring.', pin: [-1.5, 52.5], ch: [{ n: 'Yarn', o: ['#ff6f91', '#9b5de5', '#4cc3ff', '#f2c14e', 'mane'], labels: ['Pink', 'Purple', 'Blue', 'Gold', 'Mane color'] }], draw: (c, p, coat) => mBraids(p, 'hunter', c[0] === 'mane' ? coat.mane : c[0], coat.mane) }),
  IT({ id: 'M2', cat: 'mane', slot: 'mane', n: 'Dressage Button Braids', where: 'Europe and worldwide', when: 'Dressage shows, today', who: 'Dressage riders', text: 'Round "buttons" all along the neck. Some riders wrap them in white tape.', pin: [10, 50], ch: [{ n: 'Buttons', o: ['mane', '#ffffff'], labels: ['Mane color', 'White tape'] }], draw: (c, p, coat) => mBraids(p, 'buttons', c[0] === 'mane' ? coat.mane : c[0], coat.mane) }),
  IT({ id: 'M3', cat: 'mane', slot: 'mane', n: 'Shire "Flights"', where: 'Britain', when: 'Heavy horse shows', who: 'Shire and draft horse showers', text: 'Little ribbon flags on wires stand up along a braided mane.', pin: [-1.5, 53], ch: [{ n: 'Flag 1', o: ['#e8304a', '#3f6fd8', '#f2c14e', '#2fa36b'] }, { n: 'Flag 2', o: ['#f6f1e6', '#f2c14e', '#e8304a', '#3f6fd8'] }], draw: (c, p) => mBraids(p, 'flights', c[0], c[1]) }),
  IT({ id: 'M4', cat: 'mane', slot: 'rosette', n: 'Show Rosette', where: 'Horse shows everywhere', when: 'Today', who: 'Show winners', text: 'In the USA a blue ribbon means 1st place. In Britain, red is 1st!', pin: [-90, 40], thumb: [80, -252, 2.0], ch: [{ n: 'Ribbon', o: ['#3f6fd8', '#e8304a', '#f2c14e', '#f6f1e6', '#ff6f91', '#9b5de5'], labels: ['Blue (1st in the USA)', 'Red (1st in Britain)', 'Yellow', 'White', 'Pink', 'Purple'] }], draw: (c, p) => rRosette(p, c[0]) }),
  IT({ id: 'M5', cat: 'mane', slot: 'tail', n: 'Capriole Tail Bag', where: 'Vienna, Austria', when: 'Spanish Riding School tradition', who: 'Horses that do the capriole leap', text: 'Horses that do the leaping capriole have their tails braided short and tucked into a fancy tail bag.', fixed: 'Red-and-gold or green-and-gold, like the real ones.', pin: [16.4, 48.2], thumb: [-110, -116, 1.0], tailBag: 1, ch: [{ n: 'Colors', o: [['#b3162a', '#f2c14e'], ['#1f6f3c', '#f2c14e']] }], draw: null }),
  IT({ id: 'M6', cat: 'mane', slot: 'tail', n: 'Tail Ribbon', where: 'Hunts and trail rides, UK and USA', when: 'Today', who: 'Riders in groups', text: 'Safety tip: a red ribbon on a tail means "I might kick, give me space!" A green one means "I\u2019m a young horse."', pin: [-1.5, 52.5], thumb: [-106, -130, 1.6], ch: [{ n: 'Ribbon', o: ['#e8304a', '#2fa36b', 'rainbow'], labels: ['Red: "Give me space!"', 'Green: "I\u2019m young!"', 'Rainbow: just for fun'] }], draw: (c, p) => tRibbon(p, c[0]) }),
  // ---- Plumes
  IT({ id: 'P1', cat: 'plume', slot: 'plume', n: 'Knight\u2019s Parade Plume', where: 'Europe', when: '1400s to 1500s', who: 'Knights and royal parades', text: 'Fancy parade armor sometimes held a tall feather plume on the horse\u2019s head.', pin: [10, 48], ch: [{ n: 'Feather 1', o: ['#3f6fd8', '#c0392b', '#2fa36b', '#7446c4'] }, { n: 'Feather 2', o: ['#f6f1e6', '#f2c14e'] }], draw: (c, p) => pPlume(p, [c[0], c[1], c[0]]) }),
  IT({ id: 'P2', cat: 'plume', slot: 'plume', n: 'Circus Plume', where: 'London, England', when: '1768', who: 'Philip Astley, trick rider', text: 'Philip Astley did trick riding in a round ring, even standing on a galloping horse! His shows helped start the modern circus.', pin: [-0.1, 51.5], ch: [{ n: 'Feathers', o: [['#ff5fa2', '#ffd23f', '#5ad1ff'], ['#ff5fa2', '#ffffff', '#ff5fa2'], ['#ffd23f', '#ffffff', '#ffd23f'], ['#5ad1ff', '#ffffff', '#5ad1ff']], labels: ['Pink, yellow, blue', 'Pink', 'Yellow', 'Blue'] }], draw: (c, p) => pPlume(p, c[0]) }),
  IT({ id: 'P3', cat: 'plume', slot: 'plume', n: 'Marwari Kalgi', where: 'Rajasthan, India', when: 'Wedding parades', who: 'Wedding horses', text: 'A feathery head ornament for the wedding horse, matching the sparkly costume.', pin: [73, 26], ch: [{ n: 'Plume', o: ['#d7263d', '#f2c14e', '#ffffff'] }], draw: (c, p) => pKalgi(p, c[0]) }),
  // ---- Flowers
  IT({ id: 'G1', cat: 'garland', slot: 'garland', n: 'Pāʻū Island Lei', where: 'Hawaiʻi', when: '1800s to today (horses arrived in Hawaiʻi in 1803)', who: 'Pāʻū riders', text: 'Pāʻū riders wear long flowing skirts. In the Kamehameha Day parade, each island has its own color and flower lei.', fixed: 'Only the 8 island colors, like the real parade.', pin: [-157, 20.5], ch: [{ n: 'Island', o: ['#d7263d', '#ff8fb1', '#f6c343', '#9b5de5', '#3f9a5a', '#ff8c2e', '#f6f1e6', '#a8a4ae'], labels: ['Hawaiʻi: red (ʻōhiʻa lehua)', 'Maui: pink (lokelani)', 'Oʻahu: yellow (ʻilima)', 'Kauaʻi: purple (mokihana)', 'Molokaʻi: green (kukui)', 'Lānaʻi: orange (kaunaʻoa)', 'Niʻihau: white (pūpū shells)', 'Kahoʻolawe: gray (hinahina)'] }], draw: (c, p) => gGarland(p, [c[0], shade(c[0], 0.3)], { lei: 1 }) }),
  IT({ id: 'G2', cat: 'garland', slot: 'garland', n: 'Rose Parade Garland', where: 'Pasadena, California', when: 'Since January 1, 1890', who: 'The Tournament of Roses', text: 'The very first Rose Parade had horse-drawn carriages covered with fresh flowers. Riders on horseback still join every New Year\u2019s Day!', pin: [-118.1, 34.1], ch: [{ n: 'Roses', o: ['#e8304a', '#ff8fb1', '#f6f1e6', '#f6c343'] }], draw: (c, p) => gGarland(p, [c[0], shade(c[0], 0.35)]) }),
  // ---- Academy originals (pretend)
  IT({ id: 'A1', cat: 'academy', slot: 'garland', pretend: 1, n: 'Rainbow Thread Garland', where: 'Moonmeadow Riding Academy', when: 'Kimber\u2019s adventure', who: 'Made for Kimber', text: 'It shows every Ribbon thread Kimber has won back. Each Grand Stop adds a new color!', ch: [{ n: 'Sparkle', o: ['#ffffff'] }], draw: (c, p) => { const cs = RIBBON.filter((_, i) => threadsWon().includes(i)); gGarland(p, cs.length ? cs : ['#ffffff'], { thread: 1 }); } }),
  IT({ id: 'A2', cat: 'academy', slot: 'pad', pretend: 1, n: 'Starlight Saddle Pad', where: 'Moonmeadow Riding Academy', when: 'Kimber\u2019s adventure', who: 'Made for Kimber', text: 'A night-sky pad that twinkles like the Starfall Mountains.', ch: [{ n: 'Sky', o: ['#2b2f6b', '#5b3a8a', '#1f4f6b'] }], draw: (c) => bPad(c[0], { stars: 1 }) }),
  IT({ id: 'A3', cat: 'academy', slot: 'tail', pretend: 1, n: 'Comet Tail Sparkles', where: 'Moonmeadow Riding Academy', when: 'Kimber\u2019s adventure', who: 'Made for Kimber', text: 'Sparkles that trail from your horse\u2019s tail like a shooting star.', thumb: [-130, -126, 1.1], ch: [{ n: 'Sparkle', o: ['#fff6a8'] }], draw: (c, p) => tComet(p) }),
  IT({ id: 'A4', cat: 'academy', slot: 'plume', pretend: 1, n: 'Cloud-Puff Plume', where: 'Moonmeadow Riding Academy', when: 'Kimber\u2019s adventure', who: 'Made for Kimber', text: 'Fluffy as a cloud from the Lavender Sky Bridge, with rainbow streamers.', ch: [{ n: 'Cloud', o: ['#ffffff'] }], draw: (c, p) => pCloud(p) }),
  IT({ id: 'A5', cat: 'academy', slot: 'rosette', pretend: 1, n: 'Moonmeadow Rosette', where: 'Moonmeadow Riding Academy', when: 'The Midsummer Grand Parade', who: 'Kimber, who saved Moonmeadow!', text: 'The rainbow rosette for the rider who brought all seven threads home.', thumb: [80, -252, 2.0], ch: [{ n: 'Ribbon', o: ['rainbow'] }], draw: (c, p) => rRosette(p, 'rainbow') }),
];
const ITEM_BY = Object.fromEntries(ITEMS.map(i => [i.id, i]));
const REAL_ITEMS = ITEMS.filter(i => !i.pretend);
const THUMB_C = { saddle: [0, -150, 1], pad: [0, -133, 1], chest: [60, -118, 0.95], bridle: [112, -240, 1.05], mask: [112, -260, 0.9], scarf: [90, -205, 1], mane: [42, -205, 1], rosette: [80, -252, 2], tail: [-106, -130, 1.4], plume: [98, -296, 1.0], garland: [55, -150, 1] };
// unlock schedule: starters, then 2 per race (regions roughly follow the chapters)
const STARTER_ITEMS = ['S5', 'B7', 'H8', 'M1', 'M6', 'M4', 'S1', 'H3', 'C2', 'P2'];
const UNLOCK_QUEUE = ['M2', 'G2', 'S4', 'B3', 'C1', 'H4', 'C4', 'M3', 'S2', 'H1', 'S3', 'S8', 'S6', 'G1', 'B1', 'P1', 'H6', 'C6', 'B4', 'S11', 'S9', 'B2', 'H2', 'C3', 'M5', 'P3', 'S7', 'H7', 'B5', 'H5', 'C5', 'S10', 'B6'];
const ACADEMY_REWARD = { 1: 'A1', 2: 'A2', 4: 'A3', 6: 'A4', 7: 'A5' };

/* ---------- Lands, races, stops ---------- */
const LANDS = [
  { id: 0, n: 'Welcome to Moonmeadow', short: 'Paddock', thread: -1, col: '#b07bff', races: [{ n: 'Paddock Practice', stops: ['Water Trough'] }], grand: 'First Rosette', mech: 'basics', tip: 'Tap JUMP to hop over logs. Hold GALLOP to go fast!' },
  { id: 1, n: 'Apple Orchard Lane', short: 'Orchard', thread: 0, col: '#ff5a6e', races: [{ n: 'Orchard Path', stops: ['Big Red Barn', 'Cider Bridge'] }, { n: 'Ladybug Meadow', stops: ['Hay Bale Hill', 'Poppy Patch'] }, { n: 'Orchard Run', stops: ['Applewood Gate', 'Treehouse Tower'] }], grand: 'The Great Apple Tree', mech: 'logs', tip: 'Jump the logs and hay bales. Grab the horseshoes!' },
  { id: 2, n: 'Pumpkin Hollow', short: 'Pumpkins', thread: 1, col: '#ff9f43', races: [{ n: 'Leaf Pile Trail', stops: ['Scarecrow Corner', 'Pumpkin Patch'] }, { n: 'Marigold Hills', stops: ['Windy Ridge', 'Haystack Maze'] }, { n: 'Harvest Dash', stops: ['Cornfield Gate', 'Lantern Bridge'] }], grand: 'The Giant Pumpkin Barn', mech: 'forks', tip: 'New! When the path splits, tap an arrow sign to pick your path.' },
  { id: 3, n: 'Sunflower Prairie', short: 'Sunflowers', thread: 2, col: '#ffd93d', races: [{ n: 'Golden Trail', stops: ['Honeybee Hives', 'Sunflower Bridge'] }, { n: 'Windmill Way', stops: ['Prairie Pond', 'Golden Windmill'] }, { n: 'Sunbeam Sprint', stops: ['Butterfly Field', 'Haystack Hill'] }], grand: 'The Sunflower Maze', mech: 'double', tip: 'New! Double jumps: land, then tap JUMP again right away.' },
  { id: 4, n: 'Whispering Woods', short: 'Woods', thread: 3, col: '#6bd66b', races: [{ n: 'Fern Tunnel', stops: ['Mossy Log', 'Mushroom Ring'] }, { n: 'Brook Crossing', stops: ['Stepping Stones', 'Old Mill'] }, { n: 'Firefly Glen', stops: ['Owl Oak', 'Fern Falls'] }], grand: 'The Old Oak Circle', mech: 'duck', tip: 'New! Low branches: tap DUCK so Kimber leans down.' },
  { id: 5, n: 'Crystal Lake', short: 'Lake', thread: 4, col: '#4cc3ff', races: [{ n: 'Splash Shallows', stops: ['Duck Dock', 'Lily Pad Point'] }, { n: 'Lighthouse Run', stops: ['Sand Dunes', 'Lighthouse'] }, { n: 'Waterfall Steps', stops: ['Rainbow Spray', 'Pebble Beach'] }], grand: 'The Crystal Waterfall', mech: 'puddle', tip: 'New! Splash puddles slow you down. Jump them, or eat a green apple first!' },
  { id: 6, n: 'Starfall Mountains', short: 'Mountains', thread: 5, col: '#5b6cff', races: [{ n: 'Moonlit Pass', stops: ['Snowy Pines', 'Lantern Arch'] }, { n: 'Glowstone Trail', stops: ['Crystal Cave', 'Echo Bridge'] }, { n: 'Shooting Star Run', stops: ['Summit Flags', 'Star Bridge'] }], grand: 'The Star Bridge', mech: 'night', tip: 'A night ride! Glowing lanterns show where to jump.' },
  { id: 7, n: 'Lavender Sky Bridge', short: 'Sky Bridge', thread: 6, col: '#b06bff', races: [{ n: 'Cloud Steps', stops: ['Lavender Fields', 'Cloud Gate'] }, { n: 'Rainbow Ramp', stops: ['Balloon Harbor', 'Sky Garden'] }, { n: 'Whirligig\u2019s Race', stops: ['Puffy Peak', 'Cloud Castle'] }], grand: 'Cloud Castle', mech: 'clouds', tip: 'Cloud steps! Jump over the gaps between the clouds.' },
];
const THREAD_NAMES = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'];
function threadsWon() { const a = []; for (let i = 1; i <= 7; i++) if (S.prog.ch[i - 1].grand) a.push(LANDS[i].thread); return a; }
function landDone(i) { return i === 0 ? S.prog.prologue[0] > 0 : S.prog.ch[i - 1].grand; }
function landOpen(i) { if (S.set.unlockLands) return true; if (i === 0) return true; return landDone(i - 1); }
function raceStars(l, r) { return l === 0 ? S.prog.prologue[0] : S.prog.ch[l - 1].races[r]; }
function raceOpen(l, r) { if (!landOpen(l)) return false; if (S.set.unlockLands) return true; return r === 0 || raceStars(l, r - 1) > 0; }

/* ---------- lines ---------- */
const MOM_LINES = ['You\u2019ve got this, Kimber!', 'I\u2019m so proud of you.', 'Apples for your horse, cake for you!', 'Remember: big breath, then GO!', 'Win or not, you\u2019re my champion.', 'Hold on tight and have fun!', 'Look how happy your horse is!', 'You two make a great team.', 'Eyes up, heels down, big smile!', 'I\u2019ll be cheering at the finish!', 'Brave riders try their best. That\u2019s you!', 'Give your horse a pat. Good job, partner!', 'One more hug for luck!', 'You make my heart so happy.', 'Go get that thread, sweetie!', 'I love watching you ride.', 'Easy hands, kind heart. You\u2019ve got it.', 'Have a super fun ride!', 'Every jump, I\u2019m cheering for you.', 'You\u2019re learning so much!', 'Ready, set, giggle!', 'Your horse loves you. I can tell!', 'Big hug, big courage!', 'Smile at the cows if you see any!', 'Remember to breathe and enjoy it.', 'You\u2019re as brave as a lion, and twice as kind.', 'Cake after the race? Only if you want!', 'Go show the valley its colors!', 'I believe in you, Kimber.', 'Here comes the hug express!', 'You\u2019re shining brighter than the Ribbon!', 'Fast or slow, you\u2019re amazing.'];
const MOM_FACTS = ['Apples are a horse treat, just a few at a time! Cake is only for people.', 'Horses love apples, but just a little bit. Hay and grass are their main food.', 'Horses can sleep standing up!', 'A horse\u2019s teeth keep growing all its life.', 'Horses can see almost all the way around themselves!'];
const STOP_CHEERS = ['Kimber did it!', 'Way to go, Kimber!', 'Kimber is a star!', 'Amazing riding, Kimber!', 'Kimber and her horse rock!', 'Super jump, Kimber!', 'Kimber, you\u2019re on fire!', 'Hooray for Kimber!'];
const STORY = {
  p1: { t: 'Kimber and Mom arrive at Moonmeadow Riding Academy. The Rainbow Ribbon shines over the valley. "Your first day, Kimber!"', art: 'arrive' },
  p2: { t: 'In the stable, a spotted Appaloosa nuzzles Kimber. It\u2019s love at first sight! Now Kimber picks her horse and gives it a name.', art: 'stable' },
  p3: { t: 'Whoosh! Whirligig, a lonely little whirlwind, spins the Ribbon apart. Seven colored threads fly away, and the valley\u2019s colors start to fade.', art: 'scatter' },
  p4: { t: 'Before every race, Mom Kari is waiting with apples, cake and a big hug. Kimber and her horse are supercharged!', art: 'hug' },
  c1: { t: 'Chapter 1: Apple Orchard Lane. The red thread is tangled in the Great Apple Tree. Let\u2019s gallop through the orchard!', art: 'land', land: 1 },
  c2: { t: 'Chapter 2: Pumpkin Hollow. The orange thread blew past the pumpkins. Watch for paths that split in two!', art: 'land', land: 2 },
  c3: { t: 'Chapter 3: Sunflower Prairie. The yellow thread is wrapped around a giant sunflower. Get ready for double jumps!', art: 'land', land: 3 },
  c4: { t: 'Chapter 4: Whispering Woods. The green thread floated into the old oaks. Duck under the low branches!', art: 'land', land: 4 },
  c5: { t: 'Chapter 5: Crystal Lake. The blue thread sparkles by the waterfall. Splash, splash!', art: 'land', land: 5 },
  c6: { t: 'Chapter 6: Starfall Mountains. The indigo thread glows on the Star Bridge. A night ride with lanterns!', art: 'land', land: 6 },
  c7: { t: 'Chapter 7: Lavender Sky Bridge. Whirligig zoomed up into the clouds with the last thread. Time for the final race!', art: 'land', land: 7 },
  f1: { t: 'At Cloud Castle, Kimber finds Whirligig crying. "Nobody invited me to the Midsummer Parade," she sniffs. "I just wanted to play."', art: 'cry' },
  f2: { t: 'Kimber smiles. "You can come to the parade with us! Everybody should get to be in a parade." Whirligig spins with joy and says sorry.', art: 'invite' },
  f3: { t: 'Together they weave all seven threads back into the sky. The Rainbow Ribbon shines again, and every color comes home!', art: 'weave' },
  f4: { t: 'It\u2019s time for the Midsummer Grand Parade! Mom is cheering, Whirligig is waving the flags, and Kimber rides in front. Kimber saved Moonmeadow!', art: 'paradeIntro' },
};
// kind-words filter (encoded so the list isn't sitting in plain text)
const _BW = JSON.parse(atob('eyJleCI6WyJhc3MiLCJmYXQiLCJkaWUiLCJraWxsIiwiZGVhZCIsImhhdGUiLCJ1Z2x5IiwiZHVtYiIsImNyYXAiLCJqZXJrIiwibG9zZXIiLCJzdWNrcyIsInN1Y2siLCJwb29wIiwiYnV0dCIsImhlbGwiLCJkYW1uIiwibmVyZCIsIndlaXJkbyIsImZyZWFrIiwic2x1dCIsImhvZSIsImRpY2siLCJjb2NrIiwidGl0IiwiZ3VuIiwiYmxvb2QiXSwic3ViIjpbInN0dXBpZCIsImlkaW90IiwibW9yb24iLCJmdWNrIiwic2hpdCIsImJpdGNoIiwiYmFzdGFyZCIsInB1c3N5IiwiYXNzaG9sZSIsImRvdWNoZSIsIndob3JlIiwibmF6aSIsInJldGFyZCIsImRpbXdpdCIsImR1bWJvIiwiaGF0ZXIiLCJraWxsZXIiXX0='));
function nameIsKind(name) { const s = name.toLowerCase().replace(/[^a-z ]/g, ''); const sq = s.replace(/ /g, '');
  for (const w of _BW.sub) if (sq.includes(w)) return false;
  for (const t of s.split(' ').filter(Boolean)) { for (const v of [t, t.replace(/s$/, ''), t.replace(/(y|ie|er|es)$/, '')]) if (_BW.ex.includes(v)) return false; }
  return true; }
const NAME_IDEAS = ['Comet', 'Pepper', 'Freckles', 'Dottie', 'Sprinkles', 'Biscuit', 'Clover', 'Starlight', 'Maple', 'Pebbles', 'Sunny', 'Willow'];
