/* ===================== MOM'S TRUCK & TRAILER GARAGE: free customizing of the silver ~1999 "Toyoda Tacomo" + Show-Off Drive ===================== */
// every option is FREE. [label, chapter needed (landDone), value]
const TRUCK_CATS = [
  { id: 'lift', n: 'Lift', o: [['Stock', 0, 0], ['Little Lift', 1, 10], ['Big Lift', 2, 18], ['Monster Lift', 5, 30]] },
  { id: 'tires', n: 'Tires', o: [['Stock', 0, 0], ['All-Terrain', 1, 1], ['Giant Mud Tires', 2, 2], ['Flower-Tread', 5, 3]] },
  { id: 'rims', n: 'Rims', o: [['Silver', 0, '#e6e9ee'], ['Glitter Pink', 1, '#ff8fb1'], ['Gold Horseshoe', 4, '#f2c14e'], ['Rainbow', 5, 'rainbow']] },
  { id: 'paint', n: 'Paint', o: [['Factory Silver', 0, '#c9ced6'], ['Lilac', 1, '#c7b8ef'], ['Ocean Blue', 3, '#7fc4f0'], ['Mint', 4, '#9fe6c4'], ['Sunset Orange', 5, '#ffb27a'], ['Sparkle Silver', 6, '#dfe3ea']] },
  { id: 'decal', n: 'Decals', o: [['None', 0, 0], ['Rainbow Ribbon', 1, 1], ['Appaloosa Spots', 3, 2], ['Hearts & Shoes', 4, 3], ['Horse\u2019s Name', 5, 4]] },
  { id: 'x', n: 'Extras', multi: 1, o: [['Roof Light Bar', 1, 'lightbar'], ['Neigh Horn', 1, 'neigh'], ['Hay-Bale Rack', 1, 'hay'], ['Rainbow Underglow', 2, 'underglow'], ['Horse Hood Ornament', 2, 'ornament'], ['Spoiler', 4, 'spoiler'], ['Snorkel', 4, 'snorkel'], ['Bull Bar', 5, 'bullbar']] },
  { id: 'tr', n: 'Trailer', multi: 1, o: [['Matching Trailer', 1, 'trailer'], ['Comfy Padding & Fan', 4, 'comfy'], ['Trailer Nameplate', 3, 'plate']] },
];
function partOpen(ch) { return ch <= 0 ? true : ch <= 1 ? landDone(1) || S.set.unlockLands || S.set.unlockAll : landDone(ch) || S.set.unlockAll; }
function truckOpts() { const p = S.truck.p, o = {}; for (const c of TRUCK_CATS) { if (c.multi) { for (const [, , v] of c.o) o[v] = !!p[v]; } else o[c.id] = c.o[p[c.id] || 0][2]; } return o; }
function truckStyle() { const p = S.truck.p; let n = 0; for (const c of TRUCK_CATS) { if (c.multi) { for (const [, , v] of c.o) if (p[v]) n++; } else if (p[c.id]) n++; } return n; }
function driveTokens() { return (S.truck.tok || 0) + (S.truck.day !== today() ? 1 : 0); }
function driveMult() { if (driveTokens() > 0) return 2; const r = S.truck.rep; const n = r && r.d === today() ? r.n : 0; return n === 0 ? 1 : n === 1 ? 0.5 : 0.25; }
function useDrive() { const m = driveMult(); if (m === 2) { if (S.truck.tok > 0) S.truck.tok--; else S.truck.day = today(); } else { const r = S.truck.rep; if (!r || r.d !== today()) S.truck.rep = { d: today(), n: 1 }; else r.n++; } return m; }
function tacomo(x, y, s, o = {}) { g.save(); g.translate(x, y); g.scale(s, s); const t = o.t || 0;
  const r = o.tires >= 2 ? 34 : o.tires === 1 ? 28 : 24, lift = o.lift || 0, base = -r - 6 - lift, SIL = o.paint || '#c9ced6', SILD = shade(SIL, -0.22);
  if (o.underglow) for (let i = 0; i < 7; i++) fillOnly(() => E(0, -4 - i * 0.5, 170 - i * 14, 10 + (6 - i)), rgba(RIBBON[(i + Math.floor(t * 6)) % 7], 0.3));
  groundShadow(0, 0, 160, 10, 0.25);
  if (lift) for (const wx of [-88, 92]) { strokeOnly(() => { g.moveTo(wx - 14, base + 4); g.lineTo(wx - 4, -r); g.moveTo(wx + 14, base + 4); g.lineTo(wx + 4, -r); }, '#ff6fa5', 6); strokeOnly(() => { for (let k = 0; k < 4; k++) { g.moveTo(wx - 16 + k * 2, base + 8 + k * (lift / 5)); g.lineTo(wx + 16 - k * 2, base + 12 + k * (lift / 5)); } }, INK, 2); }
  const bed = () => { g.moveTo(-156, base - 48); g.lineTo(-22, base - 48); g.lineTo(-22, base); g.lineTo(-150, base); g.quadraticCurveTo(-158, base, -158, base - 8); g.closePath(); };
  const cab = () => { g.moveTo(-22, base - 52); g.lineTo(-20, base - 98); g.quadraticCurveTo(-18, base - 104, -10, base - 104); g.lineTo(30, base - 104); g.quadraticCurveTo(38, base - 104, 42, base - 98); g.lineTo(66, base - 56); g.lineTo(140, base - 50); g.quadraticCurveTo(156, base - 48, 158, base - 34); g.lineTo(158, base - 8); g.quadraticCurveTo(158, base, 150, base); g.lineTo(-22, base); g.closePath(); };
  group([[bed, SIL], [cab, SIL]], 3.2); fillOnly(() => g.rect(-156, base - 12, 314, 12), 'rgba(80,90,110,.18)'); if (o.sparkle || o.paint === '#dfe3ea') for (let i = 0; i < 6; i++) sparkle(-130 + i * 50, base - 30 + (i % 2) * 14, 3 + Math.sin(t * 4 + i) * 1.5);
  // windows with Mom driving and Kimber riding along (seatbelts on!)
  shape(() => { g.moveTo(-12, base - 96); g.lineTo(28, base - 96); g.lineTo(52, base - 58); g.lineTo(-12, base - 58); g.closePath(); }, '#bfe6ff', 2.4);
  if (o.riders) { clipTo(() => { g.moveTo(-12, base - 96); g.lineTo(28, base - 96); g.lineTo(52, base - 58); g.lineTo(-12, base - 58); g.closePath(); }, () => { shape(() => C(26, base - 70, 13), KIM.skin, 2); shape(() => { g.moveTo(13, base - 72); g.quadraticCurveTo(14, base - 92, 26, base - 88); g.quadraticCurveTo(40, base - 92, 40, base - 70); g.quadraticCurveTo(36, base - 82, 26, base - 82); g.quadraticCurveTo(16, base - 82, 13, base - 72); g.closePath(); }, '#5a3424', 1.6); fillOnly(() => C(32, base - 70, 1.6), INK);
      shape(() => C(0, base - 68, 11), KIM.skin, 2); shape(() => { g.moveTo(-11, base - 70); g.quadraticCurveTo(-10, base - 86, 0, base - 84); g.quadraticCurveTo(12, base - 86, 11, base - 70); g.quadraticCurveTo(6, base - 78, 0, base - 78); g.quadraticCurveTo(-6, base - 78, -11, base - 70); g.closePath(); }, KIM.hair, 1.6); fillOnly(() => C(5, base - 68, 1.5), '#3a78d8');
      strokeOnly(() => { g.moveTo(-8, base - 60); g.lineTo(8, base - 74); }, '#3b3640', 2.5); const wv = Math.sin(t * 8) * 4; shape(() => C(-4 + wv, base - 92, 5), KIM.skin, 1.5); }); }
  else strokeOnly(() => { g.moveTo(-4, base - 70); g.lineTo(14, base - 92); }, 'rgba(255,255,255,.8)', 3);
  strokeOnly(() => { g.moveTo(-22, base - 52); g.lineTo(-22, base); g.moveTo(60, base - 54); g.lineTo(60, base - 6); }, SILD, 2); shape(() => RR(44, base - 46, 12, 4, 2), SILD, 1.4);
  shape(() => { g.moveTo(54, base - 64); g.lineTo(66, base - 66); g.lineTo(66, base - 56); g.lineTo(56, base - 56); g.closePath(); }, '#8a8f99', 2);
  if (o.decal === 1) for (let i = 0; i < 7; i++) strokeOnly(() => { g.moveTo(-154, base - 30 + i * 2.6); g.bezierCurveTo(-90, base - 40 + i * 2.6, -10, base - 18 + i * 2.6, 156, base - 34 + i * 2.6); }, RIBBON[i], 2.8);
  if (o.decal === 2) { const rr = srng(4); for (let i = 0; i < 22; i++) fillOnly(() => E(-150 + rr() * 300, base - 44 + rr() * 36, 4 + rr() * 4, 3 + rr() * 3, rr()), '#5a3424'); }
  if (o.decal === 3) for (let i = 0; i < 6; i++) { if (i % 2) shape(() => heart(-130 + i * 50, base - 24, 7), '#ff6f91', 1.5); else horseshoe(-130 + i * 50, base - 26, 7, '#f2c14e'); }
  if (o.decal === 4 && o.name) text(o.name, 100, base - 26, 16, '#7446c4', { fam: F.title, w: 400, stroke: '#fff', sw: 4, max: 90 });
  text('TACOMO', -96, base - 36, 13, shade(SIL, -0.38), { fam: F.title, w: 400 });
  shape(() => RR(146, base - 46, 12, 12, 3), '#fff3a8', 2); fillOnly(() => C(158, base - 40, 16), 'rgba(255,243,168,.25)'); shape(() => RR(-160, base - 44, 8, 14, 2), '#ff5a6e', 2);
  shape(() => RR(-164, base - 8, 30, 10, 4), '#e6e9ee', 2.4); shape(() => RR(136, base - 10, 30, 12, 4), '#e6e9ee', 2.4);
  for (const wx of [-88, 92]) { fillOnly(() => { g.arc(wx, -r, r + 8, Math.PI, 0); g.lineTo(wx + r + 8, base + 2); g.lineTo(wx - r - 8, base + 2); g.closePath(); }, '#2a2630'); strokeOnly(() => g.arc(wx, base + 2 > -r ? -r : base + 2, r + 9, Math.PI, 0), INK, 3); }
  for (const wx of [-88, 92]) { const cy = -r; g.save(); g.translate(wx, cy); g.rotate(o.spin || 0);
    if (o.tires >= 2) for (let k = 0; k < 14; k++) { g.rotate(TAU / 14); shape(() => RR(-6, -r - 4, 12, 10, 2), '#2a2630', 2); }
    shape(() => C(0, 0, r), '#2a2630', 3); strokeOnly(() => C(0, 0, r - 5), '#3d3844', 3); if (o.tires === 3) for (let k = 0; k < 6; k++) { const a = k * TAU / 6; fillOnly(() => C(Math.cos(a) * (r - 6), Math.sin(a) * (r - 6), 3), '#ff8fb1'); }
    const rim = o.rims === 'rainbow' ? '#ffffff' : o.rims || '#e6e9ee'; shape(() => C(0, 0, r * 0.55), rim, 2.4); for (let k = 0; k < 5; k++) { const a = k * TAU / 5; strokeOnly(() => { g.moveTo(0, 0); g.lineTo(Math.cos(a) * r * 0.5, Math.sin(a) * r * 0.5); }, o.rims === 'rainbow' ? RIBBON[k] : shade(rim, -0.25), 3); } shape(() => C(0, 0, 4), '#fff', 1.5); g.restore();
    if (o.rims === '#ff8fb1') { sparkle(wx - 6, cy - 8, 4); sparkle(wx + 8, cy + 4, 3); } if (o.rims === '#f2c14e') horseshoe(wx, cy, 6, '#fff3a8'); }
  if (o.bullbar) { const p = () => { g.moveTo(160, base - 6); g.lineTo(172, base - 6); g.lineTo(172, base - 52); g.lineTo(150, base - 52); }; strokeOnly(p, INK, 9); strokeOnly(p, '#3b3640', 5); }
  if (o.snorkel) { const p = () => { g.moveTo(96, base - 24); g.lineTo(96, base - 54); g.lineTo(72, base - 98); g.lineTo(72, base - 112); }; strokeOnly(p, INK, 8); strokeOnly(p, '#3b3640', 4.5); shape(() => RR(64, base - 120, 18, 10, 4), '#3b3640', 2); }
  if (o.lightbar) { shape(() => RR(-14, base - 116, 50, 10, 4), '#3b3640', 2.2); for (let k = 0; k < 5; k++) fillOnly(() => C(-6 + k * 9, base - 111, 3.5), '#fff3a8'); fillOnly(() => E(12, base - 111, 44, 14), 'rgba(255,243,168,.25)'); }
  if (o.hay) { for (let k = 0; k < 3; k++) { const hx = -146 + k * 40, hy = base - 48; shape(() => RR(hx, hy - (k === 1 ? 52 : 26), 38, 26, 5), '#f2cf6a', 2.4); } for (let k = 0; k < 3; k++) strokeOnly(() => { const hx = -146 + k * 40, hy = base - 48 - (k === 1 ? 52 : 26); g.moveTo(hx + 12, hy); g.lineTo(hx + 12, hy + 26); g.moveTo(hx + 26, hy); g.lineTo(hx + 26, hy + 26); }, '#c0392b', 2); }
  if (o.spoiler) { strokeOnly(() => { g.moveTo(-150, base - 48); g.lineTo(-146, base - 62); g.moveTo(-130, base - 48); g.lineTo(-132, base - 62); }, INK, 3); shape(() => { g.moveTo(-162, base - 70); g.lineTo(-120, base - 66); g.lineTo(-122, base - 60); g.lineTo(-160, base - 62); g.closePath(); }, '#ff6fa5', 2.4); }
  if (o.ornament) { g.save(); g.translate(132, base - 50); g.scale(0.11, 0.11); g.translate(-80, 120); g.fillStyle = '#f2c14e'; g.strokeStyle = INK; g.lineWidth = 22; for (const f of [H_neck, H_skull, H_muzzle, H_bridge, H_earN]) { g.beginPath(); f(); g.stroke(); } for (const f of [H_neck, H_skull, H_muzzle, H_bridge, H_earN]) { g.beginPath(); f(); g.fill(); } g.restore(); }
  if (o.neigh && o.honkT > 0) { for (let i = 0; i < 3; i++) strokeOnly(() => g.arc(170, base - 40, 14 + i * 10 + (1 - o.honkT) * 20, -0.6, 0.6), 'rgba(255,255,255,.9)', 3); }
  g.restore(); }
function trailerArt(x, y, s, o = {}) { g.save(); g.translate(x, y); g.scale(s, s); const r = 22, base = -r - 8, col = o.trailer ? (o.paint || '#c9ced6') : '#e8e2d6';
  strokeOnly(() => { g.moveTo(100, base - 10); g.lineTo(150, base - 6); }, INK, 5); groundShadow(0, 0, 100, 8, 0.2);
  shape(() => { g.moveTo(-100, base); g.lineTo(-100, base - 110); g.quadraticCurveTo(-100, base - 124, -86, base - 124); g.lineTo(80, base - 124); g.quadraticCurveTo(104, base - 124, 104, base - 96); g.lineTo(104, base); g.closePath(); }, col, 3);
  if (o.trailer && o.decal === 1) for (let i = 0; i < 7; i++) strokeOnly(() => { g.moveTo(-98, base - 30 + i * 2.6); g.lineTo(102, base - 40 + i * 2.6); }, RIBBON[i], 2.6);
  if (o.trailer && o.decal === 2) { const rr = srng(6); for (let i = 0; i < 14; i++) fillOnly(() => E(-90 + rr() * 180, base - 60 + rr() * 50, 4 + rr() * 3, 3 + rr() * 2, rr()), '#5a3424'); }
  // window with Kimber's horse peeking out
  shape(() => RR(20, base - 106, 60, 40, 8), '#3b3046', 2.4); const hr = HORSE(); if (hr) clipTo(() => RR(20, base - 106, 60, 40, 8), () => drawHorseC(hr, -50, base + 116, 0.62, { pose: 'proud' }));
  if (o.comfy) { shape(() => C(-60, base - 86, 12), '#fff', 2); for (let i = 0; i < 3; i++) { g.save(); g.translate(-60, base - 86); g.rotate(i * TAU / 3 + (o.t || 0) * 6); fillOnly(() => E(0, -6, 3, 6), '#4cc3ff'); g.restore(); } }
  if (o.plate && hr) { shape(() => RR(-80, base - 52, 76, 18, 5), '#f2c14e', 2); text(hr.name, -42, base - 43, 11, '#6a4a10', { fam: F.title, w: 400, max: 70 }); }
  for (const wx of [-40, 20]) { g.save(); g.translate(wx, -r); g.rotate(o.spin || 0); shape(() => C(0, 0, r), '#2a2630', 3); shape(() => C(0, 0, r * 0.5), '#e6e9ee', 2); strokeOnly(() => { g.moveTo(-r * 0.4, 0); g.lineTo(r * 0.4, 0); }, '#9aa1ad', 2); g.restore(); }
  g.restore(); }
function rigWidth(o) { return o.trailer || true ? 520 : 330; }
// draw the whole rig: trailer + truck. (x = truck center)
function drawRig(x, y, s, o) { trailerArt(x - 270 * s, y, s * 0.95, o); tacomo(x, y, s, o); }
SC.garage = { name: 'garage', enter() { Music.play('garage'); this.t = 0; this.cat = 0; this.honkT = 0; scrollTo('tmpGarage', 0); scrollTo('tmpGcat', 0); if (!S.truck.seen) { S.truck.seen = 1; S.truck.tok = Math.max(S.truck.tok || 0, 1); save(); }
    setTimeout(() => { if (scene === this) Voice.say('garageHi', 'Welcome to my garage! Trick out my silver Tacomo any way you like. It\u2019s free! Then show it off for double horseshoes!'); }, 400); },
  update(dt) { this.t += dt; this.honkT = Math.max(0, this.honkT - dt); },
  pick(c, i) { const [label, ch, v] = c.o[i]; if (!partOpen(ch)) { SFX.no(); toast('New parts arrive after Chapter ' + ch + '!', '#3f6fd8'); return; } const p = S.truck.p;
    if (c.multi) { p[v] = !p[v]; if (v === 'neigh' && p[v]) { SFX.neighHorn(); this.honkT = 1; } else if (p[v]) { SFX.ding(i + 3); confetti(VW / 2, VH * 0.3, 14); } }
    else { p[c.id] = i; SFX.ding(i + 2); if (i) confetti(VW / 2, VH * 0.3, 14); } save(); },
  draw() { const L = lay(), u = L.u; g.fillStyle = '#aebbd6'; g.fillRect(0, 0, VW, VH); const tb = topBar('Mom\u2019s Garage', () => go(SC.build), { col: '#3f6fd8', rightW: 130 * u }); shoeCounter(L.x1 - 12, L.y0 + (tb - L.y0) / 2 - 18 * u, 36 * u, S.wallet || 0);
    const sheetH = clamp(L.port ? (L.y1 - tb) * 0.42 : L.ch * 0.7, 230, 400); let ax, ay, aw, ah, sx, sy, sw, sh;
    if (L.port) { ax = 0; ay = tb; aw = VW; ah = L.y1 - tb - sheetH - 6; sx = L.x0 + 10; sy = ay + ah; sw = L.cw - 20; sh = sheetH; } else { ax = 0; ay = tb; aw = L.x0 + L.cw * 0.55; ah = L.y1 - tb; sx = aw + 10; sy = tb + 20; sw = L.x1 - sx - 10; sh = L.y1 - sy - 10; }
    // garage interior with roll-up door to the valley
    planks(ax, ay, aw, ah * 0.72, '#aebbd6', 22); fillOnly(() => g.rect(ax, ay + ah * 0.6, aw, ah * 0.4), lin(0, ay + ah * 0.6, 0, ay + ah, [[0, '#8f96a6'], [1, '#6f7686']]));
    const dw = aw * 0.6, dh = ah * 0.42, dx = ax + aw * 0.3, dy = ay + ah * 0.08; shape(() => RR(dx, dy, dw, dh, 8), '#ccd3e0', 3); clipTo(() => RR(dx + 6, dy + 6, dw - 12, dh - 12, 6), () => { g.save(); g.translate(dx + 6, dy + 6); sky(dw - 12, dh - 12, '#8fd3ff', '#ffe9f4'); ribbon(-20, dh * 0.4, dw + 20, dh * 0.3, 6, 22, { sparkles: 4 }); hills(dw, dh * 0.7, '#a8dc8f', 6, 1, dh); hills(dw, dh * 0.8, '#7cc96b', 5, 3, dh); g.restore(); fillOnly(() => g.rect(dx + 6, dy + 6, dw - 12, dh * 0.18), '#dfe4ec'); });
    const pk = Math.min(aw * 0.18, ah * 0.35); shape(() => RR(ax + 12, dy, pk * 0.7, pk, 8), '#d9b98a', 2.4); for (let i = 0; i < 4; i++) shape(() => RR(ax + 18 + i * pk * 0.15, dy + pk * 0.6, pk * 0.1, pk * 0.3, 3), RIBBON[i * 2], 1.6);
    fillOnly(() => { g.moveTo(ax + aw / 2, ay); g.lineTo(ax + 10, ay + ah); g.lineTo(ax + aw - 10, ay + ah); g.closePath(); }, 'rgba(255,250,220,.14)');
    const o = Object.assign(truckOpts(), { t: this.t, honkT: this.honkT, name: HORSE() ? HORSE().name : '' }); const ks = Math.min(aw / 600, ah / 300); const gy = ay + ah - 16 * ks - 6;
    drawRig(ax + aw * 0.6, gy, ks, o);
    drawKimber(ax + aw * 0.1, gy + 4, ks * 0.75, { pose: 'cheer' }); drawKari(ax + aw * 0.92, gy + 4, ks * 0.75, { pose: 'open', expr: 'happy' }); if (S.foal) drawFoal(ax + aw * 0.2, gy + 6, ks * 0.75, { pose: 'stand' });
    const pt = 'Always FREE \u00b7 Show it off for 2\u00d7 horseshoes!', pfs = clamp(13 * u, 12, 17), pw2 = Math.min(aw - 20, measure(pt, pfs, F.ui, 800) + 24); shape(() => RR(ax + aw / 2 - pw2 / 2, ay + 8, pw2, pfs * 2, pfs), '#ffd93d', 2.4); text(pt, ax + aw / 2, ay + 8 + pfs, pfs, INK, { fam: F.ui, w: 800, max: pw2 - 12 });
    // customize sheet
    card(sx, sy + 14, sw, sh - 14, 'Trick out the Tacomo', '#3f6fd8', { fill: '#fffaf2', fs: clamp(17 * u, 16, 22) });
    const cfs = clamp(14 * u, 13, 18), ch = clamp(34 * u, 32, 44); const widths = TRUCK_CATS.map(c => measure(c.n, cfs, F.ui, 800) + 26); const ctot = widths.reduce((a, b) => a + b + 6, 0) + 12; const cy0 = sy + 34;
    const coff = scrollArea('tmpGcat', sx + 6, cy0, sw - 12, ch, ctot, true); pushClip(sx + 6, cy0, sw - 12, ch); let cx = sx + 12 - coff; TRUCK_CATS.forEach((c, i) => { const w = widths[i]; shape(() => RR(cx, cy0, w, ch - 2, (ch - 2) / 2), i === this.cat ? '#3f6fd8' : '#fff', 2); text(c.n, cx + w / 2, cy0 + ch / 2, cfs, i === this.cat ? '#fff' : INK, { fam: F.ui, w: 800 }); hit('gcat' + i, cx, cy0, w, ch, { fn: () => { this.cat = i; scrollTo('tmpGarage', 0); } }); cx += w + 6; }); popClip();
    const bh = clamp(56 * u, 52, 74); const oy = cy0 + ch + 8, oh = sy + sh - bh - 22 - oy; const c = TRUCK_CATS[this.cat]; const cols = L.tab || !L.port ? 2 : 2, rowH = clamp(38 * u, 36, 50), cw = (sw - 36) / cols; const rows = Math.ceil(c.o.length / cols);
    const off = scrollArea('tmpGarage', sx + 6, oy, sw - 12, oh, rows * (rowH + 6) + 6); pushClip(sx + 6, oy, sw - 12, oh);
    c.o.forEach(([label, chn, v], i) => { const x = sx + 12 + (i % cols) * (cw + 12), y = oy + 4 + Math.floor(i / cols) * (rowH + 6) - off; const open = partOpen(chn); const on = c.multi ? !!S.truck.p[v] : (S.truck.p[c.id] || 0) === i;
      shape(() => RR(x, y, cw, rowH, rowH / 2), on ? '#e3ecff' : open ? '#fff' : '#f0ecf4', 2); if (!open) icLock(x + 16, y + rowH / 2, rowH * 0.24); else if (on) { shape(() => C(x + 16, y + rowH / 2, rowH * 0.28), '#6bd66b', 1.6); icCheck(x + 16, y + rowH / 2, rowH * 0.2); } else shape(() => C(x + 16, y + rowH / 2, rowH * 0.28), '#eee', 1.6);
      text(open ? label : label + ' (Ch ' + chn + ')', x + 32, y + rowH / 2 + 1, cfs, open ? INK : '#9a8aa8', { align: 'left', fam: F.ui, w: 800, max: cw - 40 }); hit('opt_' + c.id + '_' + i, x, y, cw, rowH, { fn: () => this.pick(c, i) }); }); popClip();
    const m = driveMult(); const lab = m === 2 ? 'Show it off!  2\u00d7' : m === 1 ? 'Show-Off Drive (1\u00d7)' : 'Show-Off Drive (' + (m === 0.5 ? '\u00bd' : '\u00bc') + '\u00d7)';
    btn('showOff', sx + 14, sy + sh - bh - 10, sw - 28, bh, lab, { col: m === 2 ? '#ff9f43' : '#9b8ab8', fs: clamp(20 * u, 18, 26), icon: (ix, iy, r) => horseshoe(ix, iy + 2, r * 0.7), fn: () => go(SC.drive) });
  } };
/* ---------- Show-Off Drive: Mom drives, Kimber waves and honks; tap HONK for cheering fans, BOUNCE over bumps ---------- */
SC.drive = { name: 'drive',
  enter() { this.t = 0; this.x = 0; this.len = 5200; this.v = S.set.slow ? 150 : 185; this.road = 0; this.cheers = 0; this.splash = 0; this.y = 0; this.vy = 0; this.done = false; this.res = null; this.paused = false; this.honkT = 0; this.fx = []; this.intro = true;
    const rr = srng(Math.floor(Math.random() * 9999)); this.items = []; for (let x = 500; x < this.len - 200; x += 160 + rr() * 140) { const k = rr(); this.items.push(k < 0.3 ? { k: 'fan', x, n: 1 + Math.floor(rr() * 3), cheered: false } : k < 0.5 ? { k: 'bump', x } : k < 0.62 ? { k: 'puddle', x } : { k: 'shoe', x, hy: rr() < 0.35 ? 120 : 0, got: false }); }
    Music.play('garage'); setTimeout(() => { if (scene === this && this.intro) Voice.say('driveIntro', 'Buckle up, Kimber! I\u2019ll drive. You wave and honk at the fans, and bounce over the bumps!'); }, 400); },
  honk() { if (this.done || this.intro) return; this.honkT = 0.6; if (S.truck.p.neigh) SFX.neighHorn(); else SFX.honk(); for (const it of this.items) if (it.k === 'fan' && !it.cheered && Math.abs(it.x - this.x - 120) < 260) { it.cheered = true; const add = 2 * it.n; this.cheers += add; this.fx.push({ k: 'txt', x: it.x, s: (S.truck.p.neigh ? 'NEIGH! ' : 'Yay! ') + '+' + add, t: 0 }); SFX.ding(5); } },
  bounce() { if (this.done || this.intro || this.y > 2) return; const lift = truckOpts().lift || 0; this.vy = 520 + lift * 6; SFX.jump(); },
  key(k) { if (this.intro && (k === 'Enter' || k === ' ')) { this.intro = false; return true; } if (k === ' ' || k === 'ArrowUp') { this.bounce(); return true; } if (k === 'h' || k === 'Enter') { this.honk(); return true; } },
  update(dt) { if (this.paused || this.intro) return; this.t += dt; this.honkT = Math.max(0, this.honkT - dt); if (this.y > 0 || this.vy > 0) { this.vy -= 1500 * dt; this.y = Math.max(0, this.y + this.vy * dt); if (this.y === 0 && this.vy < 0) { this.vy = 0; SFX.land(); } }
    if (!this.done) { this.x += this.v * dt; if (Math.floor(this.t * 2) !== Math.floor((this.t - dt) * 2)) SFX.engine();
      for (const it of this.items) { const d = it.x - this.x - 60; if (it.k === 'shoe' && !it.got && Math.abs(d) < 70 && Math.abs(this.y - it.hy) < 70) { it.got = true; this.road += 2; SFX.ding(2); this.fx.push({ k: 'txt', x: it.x, s: '+2', t: 0 }); }
        if (it.k === 'bump' && !it.passed && d < 0) { it.passed = true; if (this.y > 20) { this.fx.push({ k: 'txt', x: it.x, s: 'Boing!', t: 0 }); } }
        if (it.k === 'puddle' && !it.passed && d < 0) { it.passed = true; SFX.splash(); const mud = (S.truck.p.tires || 0) >= 2; if (mud && this.y < 10) { this.splash += 2; this.fx.push({ k: 'txt', x: it.x, s: 'SPLASH! +2', t: 0 }); } } }
      if (this.x >= this.len) this.finish(); }
    for (const f of this.fx) f.t += dt; this.fx = this.fx.filter(f => f.t < 1.2); },
  finish() { this.done = true; const style = Math.min(20, truckStyle() * 2); const base = this.road + this.cheers + this.splash + style; const m = useDrive(); const pay = Math.max(1, Math.round(base * m)); const golden = earn(pay); S.truck.drives = (S.truck.drives || 0) + 1; save();
    const stars = 1 + (this.cheers >= 15 ? 1 : 0) + (style >= 12 ? 1 : 0); this.res = { base, m, pay, style, stars, golden }; SFX.fanfare(); setTimeout(() => SFX.coins(), 600); confetti(VW / 2, VH * 0.3, 80);
    Voice.say('driveDone', (m === 2 ? 'Double horseshoes! ' : '') + 'What a show! You earned ' + pay + ' horseshoes!'); },
  draw() { const L = lay(), u = L.u; const li = Math.max(1, Math.min(7, S.prog.ch.filter(c => c.grand).length + 1)); const A = LAND_ART[li]; const gy = L.port ? VH * 0.64 : VH * 0.74; const ks = L.port ? Math.min(VW / 660, VH / 1000) : Math.min(VW / 1100, VH / 560);
    g.fillStyle = lin(0, 0, 0, gy, [[0, A.sky[0]], [1, A.sky[1]]]); g.fillRect(0, 0, VW, gy); if (!A.night) sun(VW * 0.85, gy * 0.18, 22);
    for (let i = 0; i < 3; i++) cloud(((i * VW / 2.2 - this.x * 0.04) % (VW + 300) + VW + 300) % (VW + 300) - 150, gy * (0.22 + i * 0.09), 0.5 + ks * 0.6, '#fff', A.night ? 0.25 : 0.9);
    const s1 = Math.max(0.5, ks * 1.2), W1 = VW, gyF = gy - 6; const farT = sprite('dfar' + li + 'x' + W1 + 'x' + Math.round(VH) + 'g' + Math.round(gyF), W1, VH, () => landFar(li, W1, VH, gyF)); const midT = sprite('dmid' + li + 'x' + W1 + 'x' + Math.round(VH) + 'g' + Math.round(gy), W1, VH, () => landProps(li, W1, gy - 14 * s1, s1 * 0.9, 0));
    const f1 = ((this.x * ks * 0.12) % W1 + W1) % W1; blit(farT, -f1, 0, W1, VH); blit(farT, W1 - f1, 0, W1, VH); const f2 = ((this.x * ks * 0.45) % W1 + W1) % W1; blit(midT, -f2, 0, W1, VH); blit(midT, W1 - f2, 0, W1, VH);
    g.fillStyle = A.ground; g.fillRect(0, gy - 10, VW, VH); if (A.ground2) { g.fillStyle = A.ground2; g.fillRect(0, gy + 70 * ks + 30, VW, VH); }
    { const sp = 90 * ks, off = -((this.x * ks) % sp); for (let x = off; x < VW + sp; x += sp) { shape(() => RR(x - 3 * ks, gy - 40 * ks, 7 * ks, 34 * ks, 2), '#fff', 1.6); } fillOnly(() => g.rect(0, gy - 34 * ks, VW, 5 * ks), '#fff'); fillOnly(() => g.rect(0, gy - 20 * ks, VW, 5 * ks), '#fff'); }
    g.fillStyle = '#6f7686'; g.fillRect(0, gy, VW, 70 * ks); g.setLineDash([30 * ks, 26 * ks]); g.lineDashOffset = this.x * ks * 0.5; strokeOnly(() => { g.moveTo(0, gy + 35 * ks); g.lineTo(VW, gy + 35 * ks); }, '#fff3a8', 5 * ks); g.setLineDash([]); g.lineDashOffset = 0;
    { const sp = 160 * ks, off = -((this.x * ks) % sp); for (let x = off; x < VW + sp; x += sp) flower(x + 40 * ks, gy + 70 * ks + 22, 0.6 + ks * 0.4, RIBBON[(((Math.round((x - off) / sp) + Math.floor(this.x * ks / sp)) % 7) + 7) % 7]); }
    const camX = this.x - (L.port ? VW * 0.25 : VW * 0.3) / ks; const sx = wx => (wx - camX) * ks;
    for (const it of this.items) { const x = sx(it.x); if (x < -120 || x > VW + 120) continue;
      if (it.k === 'fan') { for (let i = 0; i < it.n; i++) { const fx = x + i * 40 * ks, wv = it.cheered ? Math.sin(this.t * 10 + i) * 0.5 : Math.sin(this.t * 3 + i) * 0.2; const col = RIBBON[(i + Math.floor(it.x)) % 7]; g.save(); g.translate(fx, gy - 14 * ks); g.scale(ks, ks); shape(() => RR(-10, -46, 20, 40, 8), col, 2.4); shape(() => C(0, -58, 12), KIM.skin, 2.4); strokeOnly(() => { g.moveTo(8, -40); g.lineTo(22, -66 - wv * 20); }, KIM.skin, 5); if (it.cheered) { shape(() => star(26, -76 - wv * 20, 8), '#ffd93d', 1.5); } g.restore(); } if (!it.cheered) text('\u266a', x, gy - 100 * ks, 18 * ks + 8, '#fff', { fam: F.title, w: 400, stroke: INK, sw: 3 }); }
      else if (it.k === 'bump') shape(() => { g.moveTo(x - 40 * ks, gy + 2); g.quadraticCurveTo(x, gy - 30 * ks, x + 40 * ks, gy + 2); g.closePath(); }, '#c99a62', 2.4);
      else if (it.k === 'puddle') shape(() => E(x, gy + 14 * ks, 50 * ks, 9 * ks), '#7fc4f0', 2);
      else if (it.k === 'shoe' && !it.got) horseshoe(x, gy - 40 * ks - it.hy * ks + Math.sin(this.t * 4 + it.x) * 4, 12 * ks + 4); }
    const o = Object.assign(truckOpts(), { t: this.t, honkT: this.honkT, riders: true, spin: this.x / 30, name: HORSE() ? HORSE().name : '' }); const tx = L.port ? VW - 250 * ks : VW * 0.3 + 330 * ks; const bob = Math.sin(this.t * 12) * 1.5 * (this.y > 0 ? 0 : 1);
    drawRig(tx, gy + 20 * ks - this.y * ks + bob, ks * 0.95, o); if (S.foal) drawFoal(tx - 330 * ks + Math.sin(this.t * 2) * 14, gy + 70 * ks + 26, ks * 0.95, { pose: gallopPose(this.t * 1.3) });
    for (const f of this.fx) popText(sx(f.x), gy - 140 * ks - f.t * 40, f.s, '#ff6f91', clamp(22 * u, 20, 30));
    // HUD
    const r = clamp(22 * u, 22, 30), cy = L.y0 + r + 8; ibtn('pause', L.x0 + 12 + r, cy, r, (x, y, rr) => icPause(x, y, rr), { fn: () => { this.paused = true; }, minHit: 52 });
    const fs = clamp(19 * u, 17, 26), title = 'Show-Off Drive', tw = measure(title, fs, F.title, 400) + 36; shape(() => RR(VW / 2 - tw / 2, cy - fs * 0.95, tw, fs * 1.9, fs * 0.95), '#3f6fd8', 3); text(title, VW / 2, cy + 1, fs, '#fff', { fam: F.title, w: 400, stroke: shade('#3f6fd8', -0.4), sw: 5 });
    shoeCounter(L.x1 - 12, cy - r * 0.86, r * 1.72, this.road + this.cheers + this.splash);
    const pb = Math.min(L.cw * 0.6, 300); shape(() => RR(VW / 2 - pb / 2, cy + r + 8, pb, 14, 7), '#fff', 2); fillOnly(() => RR(VW / 2 - pb / 2 + 2, cy + r + 10, (pb - 4) * clamp(this.x / this.len, 0, 1), 10, 5), '#3f6fd8');
    const R0 = clamp(48 * u, 46, 70), by = L.y1 - R0 - 16; ibtn('honk', L.x0 + R0 + 18, by, R0, (x, y, rr) => { shape(() => C(x, y, rr * 0.7), '#ffd93d', 2.5); text(S.truck.p.neigh ? '\ud83d\udc34' : '!', x, y + 1, rr * 0.8, INK, { fam: F.title, w: 400 }); }, { col: '#ff9f43', fn: () => this.honk(), label: S.truck.p.neigh ? 'NEIGH!' : 'HONK', lfs: clamp(13 * u, 12, 17), lc: '#fff', lstroke: INK });
    ibtn('bounce', L.x1 - R0 - 18, by, R0, (x, y, rr) => { strokeOnly(() => { g.moveTo(x - rr * 0.5, y + rr * 0.2); g.lineTo(x, y - rr * 0.4); g.lineTo(x + rr * 0.5, y + rr * 0.2); }, '#fff', rr * 0.25); }, { col: '#6bd66b', fn: () => this.bounce(), label: 'BOUNCE', lfs: clamp(13 * u, 12, 17), lc: '#fff', lstroke: INK });
    if (this.intro) interIntro(this, L, 'Show-Off Drive!', '#3f6fd8', [[(cx2, cy2) => { g.save(); g.translate(cx2, cy2 + 10); g.scale(0.12, 0.12); tacomo(0, 0, 1, truckOpts()); g.restore(); }, 'Mom drives the Tacomo and the trailer. You ride along with your seatbelt on!'], [(cx2, cy2) => text('\u266a', cx2, cy2, 22, '#ff9f43', { fam: F.title, w: 400 }), 'Tap HONK when you pass waving fans. Tap BOUNCE over bumps and grab horseshoes!'], [(cx2, cy2) => horseshoe(cx2, cy2, 12), driveMult() === 2 ? 'Your style bonus counts too, and this drive pays DOUBLE!' : 'Your style bonus counts too. Today\u2019s double bonus is used up, so this one pays ' + (driveMult() === 1 ? 'normal' : 'a little') + '.']],
      () => 'Mom drives the Tacomo and the trailer. You ride along with your seatbelt on! Tap honk when you pass waving fans. Tap bounce over bumps and grab horseshoes!', 'Let\u2019s roll!');
    if (this.paused) { const w = Math.min(L.cw - 40, 380), bh = clamp(60 * u, 56, 80); LAYER = 4; dim(0.5); backdropHit(null); const ht = bh * 2 + 90, x = VW / 2 - w / 2, y = L.y0 + (L.ch - ht) / 2; panel(x, y, w, ht, 24, '#fffaf2', { lw: 3.5 }); text('Paused', VW / 2, y + 36, 26, '#7446c4', { fam: F.title, w: 400 }); btn('pResume', x + 20, y + 62, w - 40, bh, 'Keep driving', { col: '#6bd66b', fn: () => { this.paused = false; } }); btn('pGarage', x + 20, y + 72 + bh, w - 40, bh, 'Back to the garage', { col: '#9b8ab8', fn: () => { this.paused = false; go(SC.garage); } }); LAYER = 0; }
    if (this.res) { const R = this.res; LAYER = 3; dim(0.4); backdropHit(null); const w = Math.min(L.cw - 24, 520), bh = clamp(58 * u, 54, 76), f2 = clamp(17 * u, 15, 22); const ht = Math.min(L.ch - 20, f2 * 9 + bh + 170); const x = VW / 2 - w / 2, y = L.y0 + (L.ch - ht) / 2;
      panel(x, y, w, ht, 24, '#fffaf2', { lw: 3.5 }); bannerRibbon(VW / 2, y + 8, Math.min(w * 0.8, 340), clamp(44 * u, 42, 56), '#3f6fd8', 'What a show!', clamp(21 * u, 18, 26)); let yy = y + clamp(44 * u, 42, 56) + 14;
      for (let i = 0; i < 3; i++) shape(() => star(VW / 2 + (i - 1) * 56 * Math.min(u, 1.3), yy + 20, 20 * Math.min(u, 1.3)), i < R.stars ? '#ffd93d' : '#f0e8f4', 3); yy += 52 * Math.min(u, 1.3);
      [['Road horseshoes', this.road], ['Fans cheering', this.cheers], ['Splash style', this.splash], ['Truck style bonus', R.style]].forEach(([s, n]) => { text(s, x + 30, yy + f2 * 0.6, f2, INK, { align: 'left', fam: F.ui, w: 800 }); text('+' + n, x + w - 30, yy + f2 * 0.6, f2, INK, { align: 'right', fam: F.title, w: 400 }); yy += f2 * 1.5; });
      const stp = R.m === 2 ? '\u00d72 GARAGE BONUS!' : R.m === 1 ? '\u00d71 (double bonus used today)' : '\u00d7' + R.m + ' (try again tomorrow for 2\u00d7)'; g.save(); g.translate(VW / 2, yy + f2); g.rotate(-0.05); text(stp, 0, 0, R.m === 2 ? f2 * 1.4 : f2 * 0.95, R.m === 2 ? '#ff6f91' : '#7a6a8a', { fam: F.title, w: 400, stroke: '#fff', sw: 5, max: w - 30 }); g.restore(); yy += f2 * 2.4;
      horseshoe(x + 44, yy + f2 * 0.8, f2 * 0.6); text('+' + R.pay + ' horseshoes', x + 64, yy + f2 * 0.8, f2 * 1.5, '#b8860b', { align: 'left', fam: F.title, w: 400, stroke: '#fff', sw: 5 }); box('drivePay', x + 20, yy, w - 40, f2 * 1.8);
      const bw = (w - 52) / 2; btn('dGarage', x + 20, y + ht - bh - 14, bw, bh, 'Garage', { col: '#3f6fd8', fn: () => go(SC.garage) }); btn('dMap', x + 32 + bw, y + ht - bh - 14, bw, bh, 'Map', { col: '#7446c4', fn: () => go(SC.map) }); LAYER = 0; }
  } };
